{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "screenshot-algo.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "screenshot-algo.fullname" . }}
  labels:
    {{- include "screenshot-algo.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "screenshot-algo.selectorLabels" . | nindent 6 }}
{{- end }}
