{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "screenshot-algo.fullname" . }}
  labels:
    {{- include "screenshot-algo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "screenshot-algo.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "screenshot-algo.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
